export const CHEVRON1_IDLING = 'CHEVRON1_IDLING';
export const CHEVRON1_ENCODED = 'CHEVRON1_ENCODED';
export const CHEVRON1_LOCKED = 'CHEVRON1_LOCKED';
export const CHEVRON1_ERRORED = 'CHEVRON1_ERRORED';

export const CHEVRON2_IDLING = 'CHEVRON2_IDLING';
export const CHEVRON2_ENCODED = 'CHEVRON2_ENCODED';
export const CHEVRON2_LOCKED = 'CHEVRON2_LOCKED';
export const CHEVRON2_ERRORED = 'CHEVRON2_ERRORED';

export const CHEVRON3_IDLING = 'CHEVRON3_IDLING';
export const CHEVRON3_ENCODED = 'CHEVRON3_ENCODED';
export const CHEVRON3_LOCKED = 'CHEVRON3_LOCKED';
export const CHEVRON3_ERRORED = 'CHEVRON3_ERRORED';

export const CHEVRON4_IDLING = 'CHEVRON4_IDLING';
export const CHEVRON4_ENCODED = 'CHEVRON4_ENCODED';
export const CHEVRON4_LOCKED = 'CHEVRON4_LOCKED';
export const CHEVRON4_ERRORED = 'CHEVRON4_ERRORED';

export const CHEVRON5_IDLING = 'CHEVRON5_IDLING';
export const CHEVRON5_ENCODED = 'CHEVRON5_ENCODED';
export const CHEVRON5_LOCKED = 'CHEVRON5_LOCKED';
export const CHEVRON5_ERRORED = 'CHEVRON5_ERRORED';

export const CHEVRON6_IDLING = 'CHEVRON6_IDLING';
export const CHEVRON6_ENCODED = 'CHEVRON6_ENCODED';
export const CHEVRON6_LOCKED = 'CHEVRON6_LOCKED';
export const CHEVRON6_ERRORED = 'CHEVRON6_ERRORED';

export const CHEVRON7_IDLING = 'CHEVRON7_IDLING';
export const CHEVRON7_ENCODED = 'CHEVRON7_ENCODED';
export const CHEVRON7_LOCKED = 'CHEVRON7_LOCKED';
export const CHEVRON7_ERRORED = 'CHEVRON7_ERRORED';
